### PR TITLE
FW 102: Revised code based on feedback

### PR DESCRIPTION
**Pull request by hzhou0**

### CODE REVIEW

**Comment by copperium** [comment]
Hey Henry, next time you don't need to create a new PR to upload changes - you can just push to your branch, and the PR on GitHub will update automatically. (You're also part of the GitHub organization now, so you can just create branches on the main repository and push them without making a fork.)

I'm a bit confused - this doesn't seem to be any different from the previous revision. Did you forget to push your changes?

**Comment by hzhou0** [comment]
My branch was updated, but the pull request wasn't. Not sure what happened here. What should I do?

**Comment by hzhou0** [comment]
Oh never mind this pull request was from my fork. Should I open another pull request?

**Comment by copperium** [comment]
Sure, making another pull request from a non-fork branch will probably work.

**Pull request closed without merging**
