### PR TITLE
[SOFT-151] Hardware-validate pedal

### PR DESCRIPTION
**Pull request by g-jessmuir**
Changes some defaults in `pedal_board` and `smoke_ads1015` as well as fix some math in `pedal_board`

### CODE REVIEW

**Review by copperium — APPROVED** [review]
LGTM

**Comment by copperium** [comment]
Actually looks like `test_data_pedal_tx` is consistently failing, needs to be looked into

**Comment by copperium** [comment]
Actually looks like `test_data_pedal_tx` is consistently failing, needs to be looked into (or just put it on the mockup branch)

**Comment by g-jessmuir** [comment]
these changes will go in on the mockup branch

**Pull request closed without merging**
